layout_spectrum: 0.850420281700421
typography_spectrum: 0.32543605000020404
color:
  brandColors:
    - '#FCFFF5'
    - '#D1DBBD'
    - '#91AA9D'
    - '#3E606F'
    - '#193441'
  brandStrength: 0.023226049756170205
  lightness: 0.5653118834304302
  saturation: 0.22555441127444553
  rhythmicContrast: 0.694625480476822
name: Kirsten Penaloza
favicon: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/ca60e670-4af3-4c59-818f-363804052b37.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/ca60e670-4af3-4c59-818f-363804052b37.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
title: Kirsten Penaloza
description: Blog
author:
  name: Kirsten Penaloza
  email: kirstenliliane@gmail.com
  url: 'https://kirstenpenaloza.com'
github: true
url: 'https://kirstenpenaloza.com'
