name: KirstenPenaloza
favicon: null
layout_spectrum: 0.23150730598717928
typography_spectrum: 0.28263832652010024
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.7616281346417964
  lightness: 0.21611986076459289
  saturation: 0.6769818898756057
  rhythmicContrast: 0.8544327958952636
purpose: []
